<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CounterDefinition"
targetNamespace="http://samples.ogsa.globus.org/counter"
xmlns="http://schemas.xmlsoap.org/wsdl/"
xmlns:counter-bindings="http://samples.ogsa.globus.org/counter/counter_bindings"
xmlns:grid-service-bindings="http://ogsa.gridforum.org/service/grid_service_bindings"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

<import location="counterBinding.wsdl"
namespace="http://samples.ogsa.globus.org/counter/counter_bindings"/>

<service name="CounterService">
<documentation>sample counter service demonstrating simple state management</documentation>

<port binding="counter-bindings:CounterSOAPBinding"
name="CounterPort">
<soap:address location="http://localhost:8080/soap/servlet/rpcrouter"/>
</port>

</service>

</definitions>
