# ----------------------------------------------------------------------
# Properties for WSIF Extensions for J2C
#
#  File: WSIFResource_JCA.properties
#  
#
# ----------------------------------------------------------------------
#
# Note to translator:
#    1. Do not translate the following words: WSIFMessage_JCAStreamable, getObjectPart
#
# Entries are of the form CONSTANT=string
#
# ----------------------------------------------------------------------
WSIF1000E=WSIF1000E: ResourceException thrown during execute method of the Interaction, check target exception for details.
WSIF1001E=WSIF1001E: Could not instantiate ''{0}'' format handler.
WSIF1002E=WSIF1002E: Exception ''{0}'' thrown during instantiation of the ''{1}'' format handler.
WSIF1003E=WSIF1003E: Exception thrown during execute method of the Interaction, check target exception for details.
WSIF1004E=WSIF1004E: Exception ''{0}'' thrown in WSIFMessage_JCAStreamable read method.
WSIF1005E=WSIF1005E: Exception ''{0}'' thrown in WSIFMessage_JCAStreamable write method.
WSIF1006E=WSIF1006E: Exception ''{0}'' thrown in the initialization of the Service SessionBean.
WSIF1007E=WSIF1007E: Exception ''{0}'' thrown in getObjectPart() method.
WSIF1008E=WSIF1008E: Exception ''{0}'' thrown during execution of the interaction, check target exception for details.
