<?xml version="1.0" ?>

<definitions targetNamespace="http://wsifservice.simpletypes/"
             xmlns:tns="http://wsifservice.simpletypes/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:jms="http://schemas.xmlsoap.org/wsdl/jms/"
             xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
             xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
             xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

	<message name="GetStringRequest">
		<part name="dummy" type="soapenc:string" />
	</message>

	<message name="GetStringResponse">
		<part name="return" type="soapenc:string" />
	</message>

	<message name="GetBooleanRequest">
		<part name="dummy" type="soapenc:boolean" />
	</message>

	<message name="GetBooleanResponse">
		<part name="return" type="soapenc:boolean" />
	</message>

	<message name="GetFloatRequest">
		<part name="dummy" type="soapenc:float" />
	</message>

	<message name="GetFloatResponse">
		<part name="return" type="soapenc:float" />
	</message>

	<message name="GetDoubleRequest">
		<part name="dummy" type="soapenc:double" />
	</message>

	<message name="GetDoubleResponse">
		<part name="return" type="soapenc:double" />
	</message>

	<message name="GetDecimalRequest">
		<part name="dummy" type="soapenc:decimal" />
	</message>

	<message name="GetDecimalResponse">
		<part name="return" type="soapenc:decimal" />
	</message>

	<message name="GetIntegerRequest">
		<part name="dummy" type="soapenc:int" />
	</message>

	<message name="GetIntegerResponse">
		<part name="return" type="soapenc:int" />
	</message>

	<message name="GetShortRequest">
		<part name="dummy" type="soapenc:short" />
	</message>

	<message name="GetShortResponse">
		<part name="return" type="soapenc:short" />
	</message>

	<message name="GetByteRequest">
		<part name="dummy" type="soapenc:byte" />
	</message>

	<message name="GetByteResponse">
		<part name="return" type="soapenc:byte" />
	</message>

	<message name="GetBase64Request">
		<part name="dummy" type="xsd:base64Binary" />
	</message>

	<message name="GetBase64Response">
		<part name="return" type="soapenc:base64" />
	</message>

	<portType name="SimplePT">
		<operation name="getString">
			<input name="getStringIn" message="tns:GetStringRequest" />
			<output name="getStringOut" message="tns:GetStringResponse" />
		</operation>

		<operation name="getBoolean">
			<input name="getBooleanIn" message="tns:GetBooleanRequest" />
			<output name="getBooleanOut" message="tns:GetBooleanResponse" />
		</operation>

		<operation name="getFloat">
			<input name="getFloatIn" message="tns:GetFloatRequest" />
			<output name="getFloatOut" message="tns:GetFloatResponse" />
		</operation>

		<operation name="getDouble">
			<input name="getDoubleIn" message="tns:GetDoubleRequest" />
			<output name="getDoubleOut" message="tns:GetDoubleResponse" />
		</operation>

		<operation name="getDecimal">
			<input name="getDecimalIn" message="tns:GetDecimalRequest" />
			<output name="getDecimalOut" message="tns:GetDecimalResponse" />
		</operation>

		<operation name="getInteger">
			<input name="getIntegerIn" message="tns:GetIntegerRequest" />
			<output name="getIntegerOut" message="tns:GetIntegerResponse" />
		</operation>

		<operation name="getShort">
			<input name="getShortIn" message="tns:GetShortRequest" />
			<output name="getShortOut" message="tns:GetShortResponse" />
		</operation>

		<operation name="getByte">
			<input name="getByteIn" message="tns:GetByteRequest" />
			<output name="getByteOut" message="tns:GetByteResponse" />
		</operation>

		<operation name="getBase64">
			<input name="getBase64In" message="tns:GetBase64Request" />
			<output name="getBase64Out" message="tns:GetBase64Response" />
		</operation>
	</portType>

	<binding name="SOAPHttpBinding" type="tns:SimplePT">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="getString">
			<soap:operation soapAction="" />
			<input name="getStringIn">
				<soap:body use="encoded" 
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output name="getStringOut">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>

		<operation name="getBoolean">
		<soap:operation soapAction="" />
			<input name="getBooleanIn">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output name="getBooleanOut">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>

		<operation name="getFloat">
		<soap:operation soapAction="" />
			<input name="getFloatIn">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output name="getFloatOut">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>

		<operation name="getDouble">
		<soap:operation soapAction="" />
			<input name="getDoubleIn">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output name="getDoubleOut">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>
		
		<operation name="getDecimal">
		<soap:operation soapAction="" />
			<input name="getDecimalIn">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output name="getDecimalOut">
				<soap:body use="encoded" 
				           namespace="http://wsifservice.simpletypes/" 
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>

		<operation name="getInteger">
		<soap:operation soapAction="" />
			<input name="getIntegerIn">
				<soap:body use="encoded" 
				           namespace="http://wsifservice.simpletypes/" 
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output name="getIntegerOut">
				<soap:body use="encoded" 
				           namespace="http://wsifservice.simpletypes/" 
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>

		<operation name="getShort">
		<soap:operation soapAction="" />
			<input name="getShortIn">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output name="getShortOut">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>

		<operation name="getByte">
		<soap:operation soapAction="" />
			<input name="getByteIn">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output name="getByteOut">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>
		
		<operation name="getBase64">
		<soap:operation soapAction="" />
			<input name="getBase64In">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output name="getBase64Out">
				<soap:body use="encoded"
				           namespace="http://wsifservice.simpletypes/"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>		
	</binding>

	<service name="SimpleService">
		<documentation>Simple service</documentation>
		<port name="SOAPPort" binding="tns:SOAPHttpBinding">
			<soap:address location="http://localhost:8080/soap/servlet/rpcrouter" />
		</port>
        <port name="AXISPort" binding="tns:SOAPHttpBinding">
            <soap:address location="http://localhost:8080/axis/services/SOAPENCSimpleTypes"/>
        </port>
	</service>

</definitions>