<?xml version="1.0" ?>

<definitions targetNamespace="http://wsifservice.stockquote/"
             xmlns:tns="http://wsifservice.stockquote/"
             xmlns:xsd="http://www.w3.org/1999/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:jms="http://schemas.xmlsoap.org/wsdl/jms/"
             xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
             xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

  <message name="GetQuoteInput">
    <part name="symbol" type="xsd:string"/>
  </message>

  <message name="GetQuoteOutput">
    <part name="quote" type="xsd:float"/>     
  </message>

  <portType name="StockquotePT">
    <operation name="getQuote">
      <input message="tns:GetQuoteInput"/>
      <output message="tns:GetQuoteOutput"/>
    </operation>
  </portType>

  <binding name="JavaBinding" type="tns:StockquotePT">
    <java:binding/>
    <format:typeMapping encoding="Java" style="Java">
      <format:typeMap typeName="xsd:string" formatType="java.lang.String" />
    </format:typeMapping>
    <operation name="getQuote">
      <java:operation
         methodName="getQuote"
         parameterOrder="symbol"
         methodType="instance" />
      <input/>
      <output/>
    </operation>
  </binding>

  <binding name="SOAPHttpBinding" type="tns:StockquotePT">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getQuote">
      <soap:operation soapAction="http://example.com/GetTradePrice"/>
      <input>
         <soap:body use="encoded" namespace="urn:xmltoday-delayed-quotes"
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
       </input>
       <output>
         <soap:body use="encoded" namespace="urn:xmltoday-delayed-quotes"
                 encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
       </output>
      </operation>
   </binding>

  <binding name="SOAPJmsBinding" type="tns:StockquotePT">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <operation name="getQuote">
      <soap:operation soapAction="http://example.com/GetTradePrice"/>
      <input>
         <soap:body use="encoded" namespace="urn:xmltoday-delayed-quotes"
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
       </input>
       <output>
         <soap:body use="encoded" namespace="urn:xmltoday-delayed-quotes"
                 encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
       </output>
      </operation>
   </binding>
   
   <binding name="NativeJmsBinding" type="tns:StockquotePT">
      <jms:binding type="ObjectMessage"/>     

        <format:typeMapping encoding="Java">
            <format:typeMap formatType="java.lang.String" typeName="xsd:string"/>
        </format:typeMapping>
        
      
      <operation name="getQuote">
      	<input>     	      		
      		<jms:property name="JMSReplyTo" part="partJmsReplyTo"/>       		
      		<jms:property name="JMSPriority" part="partJmsPriority"/>

       		<jms:body parts="symbol" use="encoded"/> 
      	</input>
      	<output>
<!--   		<jms:property name="JMSExpiration" part="expiration"/>
-->      		
     		<jms:body parts="quote" use="encoded"/>      		
      	</output>     	
      </operation>     
   </binding>

   <service name="StockquoteService">
     <documentation>Stock quote service</documentation>
     <port name="SOAPPort" binding="tns:SOAPHttpBinding">
       <soap:address location="http://localhost:8080/soap/servlet/rpcrouter"/>
     </port>
     <port name="AXISPort" binding="tns:SOAPHttpBinding">
       <soap:address location="http://localhost:8080/axis/services/Stockquote"/>
     </port>
     <port name="JavaPort" binding="tns:JavaBinding">
       <java:address className="stockquote.wsiftypes.StockQuote"/>
     </port>
     <port name="SOAPJMSPort" binding="tns:SOAPJmsBinding">
       <jms:address jndiDestinationName="SoapJmsStockquoteQueue"
                    destinationStyle="queue"
                    jndiConnectionFactoryName="WSIFSampleQCF"
                    initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                    jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="NativeJmsPort" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory" 
                   jndiProviderURL="file://C:/JNDI-Directory">
                   <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="NativeJmsResponseQueue"/>
      </jms:address>
    </port>
   </service>

</definitions>