/*
 * Copyright 2002-2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals on behalf of the Apache Software Foundation and was
 * originally based on software copyright (c) 2001, 2002, International
 * Business Machines, Inc., http://www.apache.org.  For more
 * information on the Apache Software Foundation, please see
 * <http://www.apache.org/>.
 */

/*
 *This class is automatically generated by schema to Java program.
 *Only a subset of schema is handled and some of the schema information
 *may be lost during translation
 */

package addressbook.wsiftypes;

import java.io.Serializable;

public class Address implements Serializable {

	//instance variables
	private int	streetNum;
	private java.lang.String	streetName;
	private java.lang.String	city;
	private java.lang.String	state;
	private int	zip;
	private Phone	phoneNumber;

	//constructors
	public Address () { }

	public Address (int streetNum, java.lang.String streetName, java.lang.String city, java.lang.String state, int zip, Phone phoneNumber) {
		this.streetNum	= streetNum;
		this.streetName	= streetName;
		this.city	= city;
		this.state	= state;
		this.zip	= zip;
		this.phoneNumber	= phoneNumber;
	}

	public int getStreetNum() {
		return streetNum;
	}

	public  void setStreetNum(int streetNum) {
		this.streetNum	= streetNum;
	}

	public java.lang.String getStreetName() {
		return streetName;
	}

	public  void setStreetName(java.lang.String streetName) {
		this.streetName	= streetName;
	}

	public java.lang.String getCity() {
		return city;
	}

	public  void setCity(java.lang.String city) {
		this.city	= city;
	}

	public java.lang.String getState() {
		return state;
	}

	public  void setState(java.lang.String state) {
		this.state	= state;
	}

	public int getZip() {
		return zip;
	}

	public  void setZip(int zip) {
		this.zip	= zip;
	}

	public Phone getPhoneNumber() {
		return phoneNumber;
	}

	public  void setPhoneNumber(Phone phoneNumber) {
		this.phoneNumber	= phoneNumber;
	}

	public boolean equals(Address rhs) {
		return this.streetNum == rhs.getStreetNum()
			&& this.streetName.equals(rhs.getStreetName())
			&& this.city.equals(rhs.getCity())
			&& this.state.equals(rhs.getState())
			&& this.zip	== rhs.getZip()
			&& this.phoneNumber.equals(rhs.getPhoneNumber());
	}
	
	public String toString() {
		return "streetNum=" + streetNum + "\n" + 
			"streetName=" + streetName + "\n" + 
			"city=" + city + "\n" + 
			"state=" + state + "\n" + 
			"zip=" + zip + "\n" + 
			"phoneNumber=" + phoneNumber;
	}

}
