/*
 * Copyright 2002-2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals on behalf of the Apache Software Foundation and was
 * originally based on software copyright (c) 2001, 2002, International
 * Business Machines, Inc., http://www.apache.org.  For more
 * information on the Apache Software Foundation, please see
 * <http://www.apache.org/>.
 */

/*
 *This class is automatically generated by schema to Java program.
 *Only a subset of schema is handled and some of the schema information
 *may be lost during translation
 */

package addressbook.wsiftypes;

import java.io.Serializable;

public class Phone implements Serializable {

	//instance variables
	private int	areaCode;
	private java.lang.String	exchange;
	private java.lang.String	number;

	//constructors
	public Phone () { }

	public Phone (int areaCode, java.lang.String exchange, java.lang.String number) {
		this.areaCode	= areaCode;
		this.exchange	= exchange;
		this.number	= number;
	}

	public int getAreaCode() {
		return areaCode;
	}

	public  void setAreaCode(int areaCode) {
		this.areaCode	= areaCode;
	}

	public java.lang.String getExchange() {
		return exchange;
	}

	public  void setExchange(java.lang.String exchange) {
		this.exchange	= exchange;
	}

	public java.lang.String getNumber() {
		return number;
	}

	public  void setNumber(java.lang.String number) {
		this.number	= number;
	}

	public boolean equals(Phone rhs) {
		return this.areaCode == rhs.getAreaCode()
			&& this.exchange.equals(rhs.getExchange())
			&& this.number.equals(rhs.getNumber());
	}
	
	public String toString() {
		return "areaCode=" + areaCode + "\n" + 
			"exchange=" + exchange + "\n" + 
			"number=" + number;
	}

}
