<?xml version="1.0" encoding="UTF-8"?>

<definitions name="CharTest" targetNamespace="http://chartest/"
  xmlns:tns="http://chartest/"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2000/10/XMLSchema"
  xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
  xmlns:ejb="http://schemas.xmlsoap.org/wsdl/ejb/"
  xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
  xmlns:typens="http://chartest2/" >

	<types>
	    <schema attributeFormDefault="qualified"
	        elementFormDefault="qualified"
	        targetNamespace="http://types.chartest/"
	        xmlns="http://www.w3.org/2001/XMLSchema"
	        xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	        xmlns:typens="http://chartest/">
	        <complexType name="ArrayOfChar">
	            <complexContent>
	                <restriction base="soapenc:Array">
	                    <sequence/>
	                    <attribute ref="soapenc:arrayType" wsdl:arrayType="typens:char[][]"/>
	                </restriction>
	            </complexContent>
	        </complexType>
			<element name="char" type="xsd:string" />         			
	    </schema>
	</types>

 <message name="SetCharRequest">
  <part name="in" type="typens:char"/>
 </message>

 <message name="SetCharResponse">
  <part name="out" type="xsd:boolean"/>
 </message>

 <message name="GetCharRequest">
  <part name="in" type="xsd:boolean"/>
 </message>

 <message name="GetCharResponse">
  <part name="out" type="typens:char"/>
 </message>

 <message name="SetCharArrayRequest">
  <part name="in" type="typens:ArrayOfChar"/>
 </message>

 <message name="SetCharArrayResponse">
  <part name="out" type="xsd:boolean"/>
 </message>

 <message name="GetCharArrayRequest">
  <part name="in" type="xsd:boolean"/>
 </message>

 <message name="GetCharArrayResponse">
  <part name="out" type="typens:ArrayOfChar"/>
 </message>

 <portType name="JavaPortType">

  <operation name="setCharOperation">
   <input name="in1" message="tns:SetCharRequest" />
   <output name="out1" message="tns:SetCharResponse" />
  </operation>

  <operation name="getCharOperation">
   <input name="in2" message="tns:GetCharRequest" />
   <output name="out2" message="tns:GetCharResponse" />
  </operation>

  <operation name="setCharArrayOperation">
   <input name="in3" message="tns:SetCharArrayRequest" />
   <output name="out3" message="tns:SetCharArrayResponse" />
  </operation>

  <operation name="getCharArrayOperation">
   <input name="in4" message="tns:GetCharArrayRequest" />
   <output name="out4" message="tns:GetCharArrayResponse" />
  </operation>

 </portType>

 <binding name="JavaBinding" type="tns:JavaPortType">

  <java:binding/>
  
  <format:typeMapping encoding="Java" style="Java">  
   <format:typeMap typeName="typens:char" formatType="char" />
   <format:typeMap typeName="typens:ArrayOfChar" formatType="[[C" />   
   <format:typeMap typeName="xsd:boolean" formatType="boolean" />      
  </format:typeMapping>
 
  <operation name="setCharOperation">
   <java:operation
     methodName="setChar"
     parameterOrder="in"
     methodType="instance" />
   <input name="in1"/>
   <output name="out1"/>
  </operation>

  <operation name="getCharOperation">
   <java:operation
     methodName="getChar"
     parameterOrder="in"
     methodType="instance" />
   <input name="in2"/>
   <output name="out2"/>
  </operation>

  <operation name="setCharArrayOperation">
   <java:operation
     methodName="setCharArray"
     parameterOrder="in"
     methodType="instance" />
   <input name="in3"/>
   <output name="out3"/>
  </operation>

  <operation name="getCharArrayOperation">
   <java:operation
     methodName="getCharArray"
     parameterOrder="in"
     methodType="instance" />
   <input name="in4"/>
   <output name="out4"/>
  </operation>

 </binding>
 
  <service name="JavaService">
   <documentation></documentation>
   <port binding="tns:JavaBinding" name="JavaPort">
   <java:address className="chartype.CharService" />
   </port>
  </service> 

</definitions>