<?xml version="1.0" ?>

<definitions targetNamespace="http://wsifservice.inputpartstest/"
             xmlns:tns="http://wsifservice.inputpartstest/"
             xmlns:typens="http://wsiftypes.inputpartstest/"
             xmlns:xsd="http://www.w3.org/1999/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
             xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
             xmlns:jms="http://schemas.xmlsoap.org/wsdl/jms/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

  <!-- message declns -->
  <message name="TwoPartRequestMessage">
    <part name="name" type="xsd:string"/>
    <part name="address" type="xsd:string"/>
  </message>

  <message name="TwoPartResponseMessage">
    <part name="names" type="xsd:string"/>
  </message>

  <!-- port type declns -->
  <portType name="inputpartstest">
    <operation name="inputpartstest">
      <input name="TwoPartRequest" message="tns:TwoPartRequestMessage"/>
      <output name="TwoPartResponse" message="tns:TwoPartResponseMessage"/>
    </operation>
  </portType>

  <!-- binding declns -->
  <binding name="SOAPJmsBinding" type="tns:inputpartstest">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/jms"/>
    <operation name="inputpartstest">
      <soap:operation soapAction=""/>
      <input name="TwoPartsRequest">
        <soap:body use="encoded"
                   namespace="http://wsifservice.inputpartstest/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
        <jms:propertyValue name="WSIF_FAKE" type="xsd:string" value="InputPartsTest1"/>
      </input>
      <output name="TwoPartsResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.inputpartstest/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>
  </binding>

  <!-- service decln -->
  <service name="InputPartsService">
    <port name="SOAPJMSPort" binding="tns:SOAPJmsBinding">
       <jms:address jndiDestinationName="NativeJmsRequestQueue"
                    destinationStyle="queue"
                    jndiConnectionFactoryName="WSIFSampleQCF"
                    initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                    jndiProviderURL="file:///JNDI-Directory">
                   <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="NativeJmsResponseQueue"/>
      </jms:address>
    </port>
  </service>

</definitions>