# 
# wsif.properties is used to configure WSIF.
#
# Two properties are used to override which WSIFProvider is selected when there
# exists multiple providers supporting the same namespace URI. These properties are: 
#
#    wsif.provider.default.CLASSNAME=N
#    wsif.provider.uri.M.CLASSNAME=URI
#
# CLASSNAME is the WSIFProvider class name
# N is the number of following default wsif.provider.uri.M.CLASSNAME properties 
# M is a number from 1 to N to uniquely identify each wsif.provider.uri.M.CLASSNAME
#   property key.
# For example the following two properties would override the default SOAP provider 
# to be the Apache SOAP provider:
#
# wsif.provider.default.org.apache.wsif.providers.soap.apachesoap.WSIFDynamicProvider_ApacheSOAP=1
# wsif.provider.uri.1.org.apache.wsif.providers.soap.apachesoap.WSIFDynamicProvider_ApacheSOAP=\
# http://schemas.xmlsoap.org/wsdl/soap/
#

# maximum number of milliseconds to wait for a response to a synchronous request. 
# Default value if not defined is to wait forever.
wsif.syncrequest.timeout=10000

# maximum number of seconds to wait for a response to an async request. 
# if not defined on invalid defaults to no timeout  
wsif.asyncrequest.timeout=60
wsif.servicefactory=customfactory.client.CustomServiceFactoryImpl

# whether WSIF supports unreferenced attachments. Either on or off. Default is off.
wsif.unreferencedattachments=off

# The class name of an implementation of WSIFTransactionControl that will suspend
# and resume a global transaction around a JMS put (for instance).
#wsif.transactioncontrol.impl=""
