<?xml version="1.0" ?>

<definitions targetNamespace="http://mime/"
             xmlns:tns="http://mime/"
             xmlns:xsd="http://www.w3.org/1999/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:jms="http://schemas.xmlsoap.org/wsdl/jms/"
             xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
             xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

  <!-- type defs -->
  <types>
    <xsd:schema
      targetNamespace="http://mime/"
                xmlns:xsd="http://www.w3.org/1999/XMLSchema">
      <xsd:complexType name="ArrayOfBinary">
        <complexContent>
          <restriction base="soapenc:Array">
            <attribute ref="soapenc:arrayType" arrayType="xsd:binary[]"/>
          </restriction>
        </complexContent>
      </xsd:complexType>
    </xsd:schema>
  </types>

  <message name="DataHandlerMessage">
    <part name="file" type="tns:datahandler"/>
  </message>

  <message name="DataHandlerResponse">
    <part name="return" type="tns:datahandler"/>
  </message>

  <message name="DataHandler2Message">
    <part name="return" type="tns:datahandler"/>
  </message>

  <message name="PlainTextMessage">
    <part name="plaintext" type="tns:plaintext"/>
  </message>

  <message name="Image1Message">
    <part name="image1" type="tns:image"/>
  </message>

  <message name="Image2Message">
    <part name="image2" type="tns:image"/>
  </message>

  <message name="StringMessage">
    <part name="buff" type="xsd:string"/>
  </message>

  <message name="String2Message">
    <part name="buff2" type="xsd:string"/>
  </message>

  <message name="BounceImage4Message">
    <part name="shouldBounce" type="xsd:boolean"/>
    <part name="file" type="tns:datahandler"/>
  </message>

  <message name="MultiMimePartsMessage">
    <part name="file" type="tns:datahandler"/>
    <part name="file2" type="tns:datahandler"/>
  </message>

  <message name="NullMessage">
  </message>

  <message name="ArrayOfBinaryMessage">
    <part name="file" type="tns:ArrayOfBinary"/>
  </message>

  <!-- port type declns -->
  <portType name="Mime">
    <operation name="dataHandlerToString">
      <input message="tns:DataHandlerMessage"/>
      <output message="tns:StringMessage"/>
    </operation>
    <operation name="stringToDataHandler">
      <input message="tns:StringMessage"/>
      <output message="tns:DataHandlerResponse"/>
    </operation>
    <operation name="plainTextToString">
      <input message="tns:PlainTextMessage"/>
      <output message="tns:StringMessage"/>
    </operation>
    <operation name="stringToPlainText">
      <input message="tns:StringMessage"/>
      <output message="tns:PlainTextMessage"/>
    </operation>
    <operation name="bounceImage">
      <input message="tns:Image1Message"/>
      <output message="tns:Image2Message"/>
    </operation>
    <operation name="bounceImage2">
      <input message="tns:DataHandlerMessage"/>
      <output message="tns:DataHandler2Message"/>
    </operation>
    <operation name="bounceImage4">
      <input message="tns:BounceImage4Message"/>
      <output message="tns:DataHandler2Message"/>
    </operation>
    <operation name="orMultiMimeParts">
      <input message="tns:DataHandlerMessage"/>
      <output message="tns:StringMessage"/>
    </operation>
    <operation name="andMultiMimeParts">
      <input message="tns:MultiMimePartsMessage"/>
      <output message="tns:StringMessage"/>
    </operation>
    <operation name="multiOutMimeParts">
      <input message="tns:StringMessage"/>
      <output message="tns:MultiMimePartsMessage"/>
    </operation>
    <operation name="multiInoutMimeParts">
      <input message="tns:MultiMimePartsMessage"/>
      <output message="tns:MultiMimePartsMessage"/>
    </operation>
    <operation name="noContent">
      <input message="tns:StringMessage"/>
      <output message="tns:String2Message"/>
    </operation>
    <operation name="typeStar">
      <input message="tns:DataHandlerMessage"/>
      <output message="tns:StringMessage"/>
    </operation>
    <operation name="soapBodyParts1">
      <input message="tns:BounceImage4Message"/>
      <output message="tns:StringMessage"/>
    </operation>
    <operation name="soapBodyParts2">
      <input message="tns:BounceImage4Message"/>
      <output message="tns:StringMessage"/>
    </operation>
    <operation name="soapBodyParts3">
      <input message="tns:BounceImage4Message"/>
      <output message="tns:StringMessage"/>
    </operation>
    <operation name="soapBodyParts4">
      <input message="tns:BounceImage4Message"/>
      <output message="tns:StringMessage"/>
    </operation>
    <operation name="arrayOfBinary">
      <input message="tns:ArrayOfBinaryMessage"/>
      <output message="tns:StringMessage"/>
    </operation>
  </portType>

  <!-- binding declns -->
  <binding name="SOAPHttpBinding" type="tns:Mime">
    <soap:binding style="document"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="dataHandlerToString">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="file" type="text/html"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

    <operation name="stringToDataHandler">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="return" type="text/html"/>
          </mime:part>
        </mime:multipartRelated> 
      </output>
    </operation>

    <operation name="plainTextToString">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="plaintext" type="text/plain"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

    <operation name="stringToPlainText">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="plaintext" type="text/plain"/>
          </mime:part>
        </mime:multipartRelated> 
      </output>
    </operation>

    <operation name="bounceImage">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="image1" type="image/jpeg"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="image2" type="image/jpeg"/>
          </mime:part>
        </mime:multipartRelated> 
      </output>
    </operation>

    <operation name="bounceImage2">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="file" type="image/jpeg"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="file2" type="image/jpeg"/>
          </mime:part>
        </mime:multipartRelated> 
      </output>
    </operation>
    
    <!-- bounceImage4 takes a boolean as well as an image. The boolean says
         whether the image should be returned. This allows us to test mixing
         soap and mime parts, and passing and returning null attachments -->
    <operation name="bounceImage4">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="file" type="image/jpeg"/>
          </mime:part>
          <mime:part>
            <soap:body use="encoded" parts="shouldBounce"
                       namespace="http://mime/"
                       encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="return" type="image/jpeg"/>
          </mime:part>
        </mime:multipartRelated> 
      </output>
    </operation>
    
    <!-- orMultiMimeParts tests passing in one of two different mime parts -->
    <operation name="orMultiMimeParts">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="file" type="text/html"/>
            <mime:content part="file" type="image/jpeg"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

    <!-- andMultiMimeParts tests passing in two different mime parts -->
    <operation name="andMultiMimeParts">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="file" type="text/plain"/>
          </mime:part>
          <mime:part>
            <mime:content part="file2" type="text/plain"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

    <!-- multiOutMimeParts tests returning multiple output mime parts -->
    <operation name="multiOutMimeParts">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="file" type="text/plain"/>
          </mime:part>
          <mime:part>
            <mime:content part="file2" type="text/plain"/>
          </mime:part>
        </mime:multipartRelated> 
      </output>
    </operation>

    <!-- multiInoutMimeParts tests multiple inout mime parts -->
    <operation name="multiInoutMimeParts">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="file" type="text/plain"/>
          </mime:part>
          <mime:part>
            <mime:content part="file2" type="text/plain"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="file" type="text/plain"/>
          </mime:part>
          <mime:part>
            <mime:content part="file2" type="text/plain"/>
          </mime:part>
        </mime:multipartRelated> 
      </output>
    </operation>

    <!-- Defining a mime message that doesn't contain any attachments is 
         probably valid. Anyway we allow it -->
    <operation name="noContent">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <soap:body use="encoded"
                       namespace="http://mime/"
                       encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

    <!-- Test out type="text/*" -->
    <operation name="typeStar">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
             <mime:content part="file" type="text/*"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

    <!-- Test out soap:body parts="a b c" -->
    <operation name="soapBodyParts1">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <soap:body use="encoded"
                       namespace="http://mime/"
                       encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                       parts="shouldBounce" />
          </mime:part>
          <mime:part>
             <mime:content part="file" type="text/plain"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

    <operation name="soapBodyParts2">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
             <mime:content part="file" type="text/plain"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

    <operation name="soapBodyParts3">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <soap:body use="encoded"
                       namespace="http://mime/"
                       encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                       parts="shouldBounce" />
          </mime:part>
          <mime:part>
             <mime:content part="file" type="text/plain"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

    <operation name="soapBodyParts4">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
             <mime:content part="file" type="text/plain"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

    <operation name="arrayOfBinary">
      <soap:operation soapAction=""/>
      <input>
        <mime:multipartRelated>
          <mime:part>
            <mime:content part="file" type="text/html"/>
          </mime:part>
        </mime:multipartRelated> 
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="http://mime/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>
  </binding>

  <!-- Mime/Axis/Jms is not supported at present
     binding name="SOAPJmsBinding" type="tns:Mime">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/jms"/>
  </binding -->

  <!-- service decln -->
  <service name="MimeService">
    <port name="SOAPPort" binding="tns:SOAPHttpBinding">
      <soap:address location="http://localhost:8080/soap/servlet/rpcrouter"/>
    </port>
    <port name="AXISPort" binding="tns:SOAPHttpBinding">
      <soap:address location="http://localhost:8080/axis/services/Mime"/>
    </port>
    <!-- port name="SOAPJMSPort" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port -->
  </service>

</definitions>