/*
 * Copyright 2002-2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals on behalf of the Apache Software Foundation and was
 * originally based on software copyright (c) 2001, 2002, International
 * Business Machines, Inc., http://www.apache.org.  For more
 * information on the Apache Software Foundation, please see
 * <http://www.apache.org/>.
 */

package org.apache.wsif.providers.jca.toolplugin;

/**
 * This interface allows Resource Adapter to provide a code generation contribution to the tool
 * environment. The tooling delegates to the implementation of this interface the generation
 * of all format handlers for the particular encoding and style. 
 * 
 * @author Hesham Fahmy <hfahmy@ca.ibm.com>
 * @author Piotr Przybylski <piotrp@ca.ibm.com>
 * @author Harlod Gartner
 */

public interface FormatHandlerGenerator
{
	public final static int XSD_TYPE =0;
	public final static int XSD_ELEMENT =1;

  /**
	* Generates a Custom Format Handler for a particular XSD Type or Element.
	* @param <code>generationPackage</code> The fully qualified package that the generator should use to generate its classes in.
	* @param <code>beanClass</code> The fully qualified name of the Java bean class that represents the XSD type (or element) for which a format handler is being generated.
	* @param <code>aDefinition</code> The WSDL definition from which the XSD type is derived.
	* @param <code>aBinding</code> The WSDL binding element that contains the type mapping for the XSD type that is being used.
	* @param <code>anEncoding</code> The <i>encoding</i> attribute off the TypeMapping element associated with the format handler to be generated.
	* @param <code>aStyle</code> The <i>style</i> attribute off the TypeMapping element associated with the format handler to be generated.
	* @param <code>xsdQname</code> The QName of the XSD element(or type) for which the format handler is being generated.
	* @param <code>elementType</code> The type of element represented by the <code>xsdQname</code> parameter. This is either <code>CustomFormatHandlerGenerator.XSD_TYPE</code>
	* 				or <code>CustomFormatHandlerGenerator.XSD_ELEMENT</code>. 
 	* @param <code>generationContext</code> The generation context or <code>null</code> is no context is required.
	* @return a <code>HashTable</code> that contains a set of  <code>java.io.InputStream</code> s. Each input stream contains the generated code for a particular
	* class generated by the format handler generator. The number of input streams returned depends on the number of classes that are generated by the format handler
	* generator.  The keys of the HashTable must be the name of each class (unqualified) that is represented by its corresponding InputStream value. The class name keys
	* are unqualified because they must all be in the <code>generationPackage</code> that is passed in as an input parameter.
	* @throws <code>org.apache.wsif.WSIFException</code> thrown if an error occurs during format handler generation. 
	*/

	public java.util.Hashtable generate (String generationPackage, String beanClass, javax.wsdl.Definition aDefinition,javax.wsdl.Binding aBinding, String anEncoding,
														String aStyle, javax.xml.namespace.QName xsdQname, int elementType, Object generationContext) throws org.apache.wsif.WSIFException;

	/**
	 * Creates a new context for format handler generation.
	 * The context is an optional object that can be used by a FormatHandlerGenerator to assist in code generation, or in keeping track of 
	 * artifacts generated. The details, and implementation, of the object are specific to each FormatHandlerGenerator.
	 * Tooling environments must call this method first, before invoking the FormatHandlerGenerator to generate code. The context that is returned must be used
	 * by the tooling environment for all subsequent calls to the FormatHandlerGenerator.
	 * @return A new generation context.
	 */

	public Object createGenerationContext();
}

