<?xml version="1.0" ?>

<definitions targetNamespace="http://wsifservice.addressbook/"
             xmlns:tns="http://wsifservice.addressbook/"
             xmlns:typens="http://wsiftypes.addressbook/"
             xmlns:xsd="http://www.w3.org/1999/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:jms="http://schemas.xmlsoap.org/wsdl/jms/"
             xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
             xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

  <!-- type defs -->
  <types>
    <xsd:schema
      targetNamespace="http://wsiftypes.addressbook/"
                xmlns:xsd="http://www.w3.org/1999/XMLSchema">
      <xsd:complexType name="phone">
        <xsd:element name="areaCode" type="xsd:int"/>
        <xsd:element name="exchange" type="xsd:string"/>
        <xsd:element name="number" type="xsd:string"/>
      </xsd:complexType>

      <xsd:complexType name="address">
        <xsd:element name="streetNum" type="xsd:int"/>
        <xsd:element name="streetName" type="xsd:string"/>
        <xsd:element name="city" type="xsd:string"/>
        <xsd:element name="state" type="xsd:string"/>
        <xsd:element name="zip" type="xsd:int"/>
        <xsd:element name="phoneNumber" type="typens:phone"/>
      </xsd:complexType>
    </xsd:schema>
  </types>

  <!-- message declns -->
  <message name="AddEntryRequestMessage">
    <part name="name" type="xsd:string"/>
    <part name="address" type="typens:address"/>
    <part name="requestDeliveryMode" type="xsd:int"/>
  </message>

  <message name="AddEntryResponseMessage">
  </message>

  <message name="AddEntryJmsPropRequestMessage">
    <part name="name" type="xsd:string"/>
    <part name="address" type="typens:address"/>
    <part name="requestPriority" type="xsd:int"/>
    <part name="requestReplyTo" type="xsd:string"/>
    <part name="requestDeliveryMode" type="xsd:int"/>
    <part name="requestTimeToLive" type="xsd:long"/>
  </message>

  <message name="AddEntryJmsPropResponseMessage">
  </message>

  <message name="AddEntryUserPropRequestMessage">
    <part name="name"                type="xsd:string"/>
    <part name="address"             type="typens:address"/>
    <part name="requestDeliveryMode" type="xsd:int"/>
    <part name="requestUPBoolean"    type="xsd:boolean"/>
    <part name="requestUPByte"       type="xsd:byte"/>
    <part name="requestUPShort"      type="xsd:short"/>
    <part name="requestUPInt"        type="xsd:int"/>
    <part name="requestUPLong"       type="xsd:long"/>
    <part name="requestUPFloat"      type="xsd:float"/>
    <part name="requestUPDouble"     type="xsd:double"/>
    <part name="requestUPString"     type="xsd:string"/>
    <part name="requestUPObject"     type="typens:obj"/>
  </message>

  <message name="AddEntryUserPropResponseMessage">
  </message>

  <message name="GetAddressFromNameRequestMessage">
    <part name="name" type="xsd:string"/>
    <part name="requestDeliveryMode" type="xsd:int"/>
  </message>

  <message name="GetAddressFromNameResponseMessage">
    <part name="address" type="typens:address"/>
  </message>

  <!-- port type declns -->
  <portType name="AddressBook">
    <operation name="addEntry">
      <input name="AddEntryRequest" message="tns:AddEntryRequestMessage"/>
      <output name="AddEntryResponse" message="tns:AddEntryResponseMessage"/>
    </operation>
    <operation name="addEntry">
      <input name="AddEntryJmsPropRequest" message="tns:AddEntryJmsPropRequestMessage"/>
      <output name="AddEntryJmsPropResponse" message="tns:AddEntryJmsPropResponseMessage"/>
    </operation>
    <operation name="addEntry">
      <input name="AddEntryUserPropRequest" message="tns:AddEntryUserPropRequestMessage"/>
      <output name="AddEntryUserPropResponse" message="tns:AddEntryUserPropResponseMessage"/>
    </operation>
    <operation name="getAddressFromName">
      <input name="GetAddressFromNameRequest" message="tns:GetAddressFromNameRequestMessage"/>
      <output name="GetAddressFromNameResponse" message="tns:GetAddressFromNameResponseMessage"/>
    </operation>
  </portType>

  <binding name="SOAPHttpBinding" type="tns:AddressBook">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="addEntry">
      <soap:operation soapAction=""/>
      <input name="AddEntryRequest">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" 
                   parts="name address" /> 
      </input>
      <output name="AddEntryResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" /> 
      </output>
    </operation>
    <operation name="addEntry">
      <soap:operation soapAction=""/>
      <input name="AddEntryJmsPropRequest">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" 
                   parts="name address" /> 
      </input>
      <output name="AddEntryJmsPropResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" /> 
      </output>
    </operation>
    <operation name="addEntry">
      <soap:operation soapAction=""/>
      <input name="AddEntryUserPropRequest">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" 
                   parts="name address" /> 
      </input>
      <output name="AddEntryUserPropResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </output>
    </operation>
    <operation name="getAddressFromName">
      <soap:operation soapAction=""/>
      <input name="GetAddressFromNameRequest">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                   parts="name" />
      </input>
      <output name="GetAddressFromNameResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>
  </binding>

  <binding name="JavaBinding" type="tns:AddressBook">
    <java:binding/>
    <format:typeMapping encoding="Java" style="Java">
      <format:typeMap typeName="typens:address" formatType="addressbook.wsiftypes.Address" />
      <format:typeMap typeName="xsd:string" formatType="java.lang.String" />
    </format:typeMapping>
    <operation name="addEntry">
      <java:operation
         methodName="addEntry"
         parameterOrder="name address"
         methodType="instance" />
      <input name="AddEntryJmsPropRequest"/>
      <output name="AddEntryJmsPropResponse"/>
    </operation>
    <operation name="getAddressFromName">
      <java:operation
         methodName="getAddressFromName"
         parameterOrder="name"
         methodType="instance"
         returnPart="address" />
      <input name="GetAddressFromNameRequest"/>
      <output name="GetAddressFromNameResponse"/>
    </operation>
  </binding>

  <binding name="SOAPJmsBinding" type="tns:AddressBook">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/jms"/>
    <operation name="addEntry">
      <soap:operation soapAction=""/>
      <input name="AddEntryRequest">
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </input>
      <output name="AddEntryResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </output>
    </operation>
    <operation name="addEntry">
      <soap:operation soapAction=""/>
      <input name="AddEntryJmsPropRequest">
        <jms:property name="JMSPriority"     part="requestPriority" />
        <jms:property name="JMSReplyTo"      part="requestReplyTo"  />
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <jms:property name="JMSTimeToLive"   part="requestTimeToLive" />
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </input>
      <output name="AddEntryJmsPropResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </output>
    </operation>
    <operation name="addEntry">
      <soap:operation soapAction=""/>
      <input name="AddEntryUserPropRequest">
        <jms:property name="JMSDeliveryMode"   part="requestDeliveryMode" />
        <jms:property name="MyBooleanProperty" part="requestUPBoolean" />
        <jms:property name="MyByteProperty"    part="requestUPByte" />
        <jms:property name="MyShortProperty"   part="requestUPShort" />
        <jms:property name="MyIntProperty"     part="requestUPInt" />
        <jms:property name="MyLongProperty"    part="requestUPLong" />
        <jms:property name="MyFloatProperty"   part="requestUPFloat" />
        <jms:property name="MyDoubleProperty"  part="requestUPDouble" />
        <jms:property name="MyStringProperty"  part="requestUPString" />
        <jms:property name="MyObjectProperty"  part="requestUPObject" />
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </input>
      <output name="AddEntryUserPropResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </output>
    </operation>
    <operation name="getAddressFromName">
      <soap:operation soapAction=""/>
      <input name="GetAddressFromNameRequest">
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output name="GetAddressFromNameResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>
  </binding>

  <binding name="BindPV" type="tns:AddressBook">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/jms"/>
    <operation name="addEntry">
      <soap:operation soapAction=""/>
      <input name="AddEntryRequest">
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="AddressBookReplyTo"/>
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </input>
      <output name="AddEntryResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </output>
    </operation>
    <operation name="addEntry">
      <soap:operation soapAction=""/>
      <input name="AddEntryJmsPropRequest">
        <jms:property name="JMSPriority"     part="requestPriority" />
        <jms:property name="JMSReplyTo"      part="requestReplyTo"  />
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <jms:property name="JMSTimeToLive"   part="requestTimeToLive" />
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </input>
      <output name="AddEntryJmsPropResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </output>
    </operation>
    <operation name="addEntry">
      <soap:operation soapAction=""/>
      <input name="AddEntryUserPropRequest">
        <jms:property name="JMSDeliveryMode"   part="requestDeliveryMode" />
        <jms:property name="MyBooleanProperty" part="requestUPBoolean" />
        <jms:property name="MyByteProperty"    part="requestUPByte" />
        <jms:property name="MyShortProperty"   part="requestUPShort" />
        <jms:property name="MyIntProperty"     part="requestUPInt" />
        <jms:property name="MyLongProperty"    part="requestUPLong" />
        <jms:property name="MyFloatProperty"   part="requestUPFloat" />
        <jms:property name="MyDoubleProperty"  part="requestUPDouble" />
        <jms:property name="MyStringProperty"  part="requestUPString" />
        <jms:property name="MyObjectProperty"  part="requestUPObject" />
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </input>
      <output name="AddEntryUserPropResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </output>
    </operation>
    <operation name="getAddressFromName">
      <soap:operation soapAction=""/>
      <input name="GetAddressFromNameRequest">
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="AddressBookReplyTo"/>
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output name="GetAddressFromNameResponse">
        <soap:body use="encoded"
                   namespace="http://wsifservice.addressbook/"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>
  </binding>

  <binding name="NJBindPV" type="tns:AddressBook">
    <jms:binding type="ObjectMessage"/>
    <format:typeMapping encoding="Java" style="Java">
       <format:typeMap typeName="typens:address" formatType="com.ibm.www.namespace.wsif.samples.ab.types.Address" />
       <format:typeMap typeName="xsd:string" formatType="java.lang.String" />
    </format:typeMapping>
    <operation name="addEntry">
      <input name="AddEntryRequest">
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="AddressBookReplyTo"/>
      </input>
      <output name="AddEntryResponse">
      </output>
    </operation>
    <operation name="addEntry">
      <input name="AddEntryJmsPropRequest">
        <jms:property name="JMSPriority"     part="requestPriority" />
        <jms:property name="JMSReplyTo"      part="requestReplyTo"  />
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <jms:property name="JMSTimeToLive"   part="requestTimeToLive" />
      </input>
      <output name="AddEntryJmsPropResponse">
      </output>
    </operation>
    <operation name="addEntry">
      <input name="AddEntryUserPropRequest">
        <jms:property name="JMSDeliveryMode"   part="requestDeliveryMode" />
        <jms:property name="MyBooleanProperty" part="requestUPBoolean" />
        <jms:property name="MyByteProperty"    part="requestUPByte" />
        <jms:property name="MyShortProperty"   part="requestUPShort" />
        <jms:property name="MyIntProperty"     part="requestUPInt" />
        <jms:property name="MyLongProperty"    part="requestUPLong" />
        <jms:property name="MyFloatProperty"   part="requestUPFloat" />
        <jms:property name="MyDoubleProperty"  part="requestUPDouble" />
        <jms:property name="MyStringProperty"  part="requestUPString" />
        <jms:property name="MyObjectProperty"  part="requestUPObject" />
      </input>
      <output name="AddEntryUserPropResponse">
      </output>
    </operation>
    <operation name="getAddressFromName">
      <input name="GetAddressFromNameRequest">
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="AddressBookReplyTo"/>
      </input>
      <output name="GetAddressFromNameResponse">
      </output>
    </operation>
  </binding>

  <binding name="NativeJmsBinding" type="tns:AddressBook">
    <jms:binding type="ObjectMessage"/>
    <format:typeMapping encoding="Java" style="Java">
       <format:typeMap typeName="typens:address" formatType="com.ibm.www.namespace.wsif.samples.ab.types.Address" />
       <format:typeMap typeName="xsd:string" formatType="java.lang.String" />
    </format:typeMapping>
    <operation name="addEntry">
      <input name="AddEntryRequest">
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
      </input>
      <output name="AddEntryResponse">
      </output>
    </operation>
    <operation name="addEntry">
      <input name="AddEntryJmsPropRequest">
        <jms:property name="JMSPriority"     part="requestPriority" />
        <jms:property name="JMSReplyTo"      part="requestReplyTo"  />
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <jms:property name="JMSTimeToLive"   part="requestTimeToLive" />
      </input>
      <output name="AddEntryJmsPropResponse">
      </output>
    </operation>
    <operation name="addEntry">
      <input name="AddEntryUserPropRequest">
        <jms:property name="JMSDeliveryMode"   part="requestDeliveryMode" />
        <jms:property name="MyBooleanProperty" part="requestUPBoolean" />
        <jms:property name="MyByteProperty"    part="requestUPByte" />
        <jms:property name="MyShortProperty"   part="requestUPShort" />
        <jms:property name="MyIntProperty"     part="requestUPInt" />
        <jms:property name="MyLongProperty"    part="requestUPLong" />
        <jms:property name="MyFloatProperty"   part="requestUPFloat" />
        <jms:property name="MyDoubleProperty"  part="requestUPDouble" />
        <jms:property name="MyStringProperty"  part="requestUPString" />
        <jms:property name="MyObjectProperty"  part="requestUPObject" />
      </input>
      <output name="AddEntryUserPropResponse">
      </output>
    </operation>
    <operation name="getAddressFromName">
      <input name="GetAddressFromNameRequest">
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
      </input>
      <output name="GetAddressFromNameResponse">
      </output>
    </operation>
  </binding>

  <binding name="SSOutProperties" type="tns:AddressBook">
    <jms:binding type="ObjectMessage"/>
    <format:typeMapping encoding="Java" style="Java">
       <format:typeMap typeName="typens:address" formatType="com.ibm.www.namespace.wsif.samples.ab.types.Address" />
       <format:typeMap typeName="xsd:string" formatType="java.lang.String" />
    </format:typeMapping>
    <operation name="addEntry">
      <input name="AddEntryRequest">
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
      </input>
      <output name="AddEntryResponse">
      </output>
    </operation>
    <operation name="addEntry">
      <input name="AddEntryJmsPropRequest">
        <jms:property name="JMSPriority"     part="requestPriority" />
        <jms:property name="JMSReplyTo"      part="requestReplyTo"  />
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
        <jms:property name="JMSTimeToLive"   part="requestTimeToLive" />
      </input>
      <output name="AddEntryJmsPropResponse">
      </output>
    </operation>
    <operation name="addEntry">
      <input name="AddEntryUserPropRequest">
        <jms:property name="JMSDeliveryMode"   part="requestDeliveryMode" />
        <jms:property name="MyBooleanProperty" part="requestUPBoolean" />
        <jms:property name="MyByteProperty"    part="requestUPByte" />
        <jms:property name="MyShortProperty"   part="requestUPShort" />
        <jms:property name="MyIntProperty"     part="requestUPInt" />
        <jms:property name="MyLongProperty"    part="requestUPLong" />
        <jms:property name="MyFloatProperty"   part="requestUPFloat" />
        <jms:property name="MyDoubleProperty"  part="requestUPDouble" />
        <jms:property name="MyStringProperty"  part="requestUPString" />
        <jms:property name="MyObjectProperty"  part="requestUPObject" />
      </input>
      <output name="AddEntryUserPropResponse">
      </output>
    </operation>
    <operation name="getAddressFromName">
      <input name="GetAddressFromNameRequest">
        <jms:property name="JMSDeliveryMode" part="requestDeliveryMode" />
      </input>
      <output name="GetAddressFromNameResponse">
        <jms:property name="userOutProperty1" part="userOutPropPart1" />
        <jms:property name="userOutProperty2" part="userOutPropPart2" />
      </output>
    </operation>
  </binding>

  <!-- service decln -->
  <service name="AddressBookService">
    <port name="default" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="baddefault" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="default-alt" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jmsProviderDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-qcfmixq" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="WSIFSampleQCF"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="SoapJmsAddressBookQueue"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-mixq" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="WSIFSampleQCF"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-mixicf" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.ibm.wsif.test.WSIFTestRunner"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-qcf" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="trash"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-queue" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="trash"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-altqueue" binding="tns:SOAPJmsBinding">
      <jms:address jmsProviderDestinationName="trash"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-style" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="trash"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-icf" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="trash"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-jurl" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="trash">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-noq" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-nostyle" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="SoapJmsAddressBookQueue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-noqcf" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-noicfjurl" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-altandq" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="SoapJmsAddressBookQueue"
                   jmsProviderDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-topic" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="topic"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-implspec" binding="tns:SOAPJmsBinding">
      <jms:address jmsImplementationSpecificURI="mq://qmgr/qname">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-mqandjndi" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"
                   jmsImplementationSpecificURI="mq://qmgr/qname">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-nothing" binding="tns:SOAPJmsBinding">
      <jms:address >
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bad-nobinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="SOAP-http-noattrs" binding="tns:SOAPHttpBinding">
      <soap:address location="http://localhost:8080/soap/servlet/rpcrouter"/>
    </port>
    <port name="AXIS-http-noattrs" binding="tns:SOAPHttpBinding">
      <soap:address location="http://localhost:8080/axis/services/AddressBook"/>
    </port>
    <port name="java-noattrs" binding="tns:JavaBinding">
      <java:address className="addressbook.wsiftypes.AddressBook"/>
    </port>
    <port name="bad-persist" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="nonpersist" binding="tns:SOAPJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="addrpv" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="AddressBookReplyTo"/>
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="bindpv" binding="tns:BindPV">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="adbipv" binding="tns:BindPV">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="trash"/>
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="ovpv" binding="tns:SOAPJmsBinding">
      <jms:address jndiDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="trash"/>
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="timeout" binding="tns:SOAPJmsBinding">
      <jms:address jmsProviderDestinationName="SYSTEM.DEAD.LETTER.QUEUE"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="SOAPAction" type="xsd:string" value=" "/>
      </jms:address>
    </port>
    <port name="NJdefault" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbaddefault" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJdefault-alt" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jmsProviderDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-qcfmixq" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="WSIFSampleQCF"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="NativeJmsRequestQueue"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-mixq" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="WSIFSampleQCF"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-mixicf" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.ibm.wsif.test.WSIFTestRunner"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-qcf" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="trash"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-queue" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="trash"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-altqueue" binding="tns:NativeJmsBinding">
      <jms:address jmsProviderDestinationName="trash"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-style" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="trash"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-icf" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="trash"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-jurl" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="trash"/>
    </port>
    <port name="NJbad-noq" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-nostyle" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="NativeJmsRequestQueue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-noqcf" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-noicfjurl" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"/>
    </port>
    <port name="NJbad-altandq" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="NativeJmsRequestQueue"
                   jmsProviderDestinationName="SoapJmsAddressBookQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-topic" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="topic"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-implspec" binding="tns:NativeJmsBinding">
      <jms:address jmsImplementationSpecificURI="mq://qmgr/qname"/>
    </port>
    <port name="NJbad-mqandjndi" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"
                   jmsImplementationSpecificURI="mq://qmgr/qname"/>
    </port>
    <port name="NJbad-nothing" binding="tns:NativeJmsBinding">
      <jms:address />
    </port>
    <port name="NJbad-nobinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJbad-persist" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJnonpersist" binding="tns:NativeJmsBinding">
      <jms:address jmsVendorURI="http://ibm.com/ns/mqseries"
                   jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="NJaddrpv" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="AddressBookReplyTo"/>
      </jms:address>
    </port>
    <port name="NJbindpv" binding="tns:NJBindPV">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
      </jms:address>
    </port>
    <port name="NJadbipv" binding="tns:NJBindPV">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="trash"/>
      </jms:address>
    </port>
    <port name="NJovpv" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="TempQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory">
        <jms:propertyValue name="JMSReplyTo" type="xsd:string" value="trash"/>
      </jms:address>
    </port>
    <port name="NJtimeout" binding="tns:NativeJmsBinding">
      <jms:address jmsProviderDestinationName="SYSTEM.DEAD.LETTER.QUEUE"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
    <port name="SSOutProperties" binding="tns:SSOutProperties">
      <jms:address jmsProviderDestinationName="SYSTEM.DEAD.LETTER.QUEUE"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file:///JNDI-Directory"/>
    </port>
  </service>

</definitions>

