<?xml version="1.0" ?>

<definitions targetNamespace="http://jms/"
             xmlns:tns="http://jms/"
             xmlns:xsd="http://www.w3.org/1999/XMLSchema"
             xmlns:jms="http://schemas.xmlsoap.org/wsdl/jms/"
             xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

  <!-- message declns -->
  <message name="SimpleReq">
    <part name="choice" type="xsd:int"/>
  </message>
  
  <message name="SimpleResp"/>
  
  <message name="SimpleFault">
    <part name="faultText" type="xsd:string"/>
  </message>
  
  <message name="IntFault">
    <part name="faultInt1" type="xsd:int"/>
    <part name="faultInt2" type="xsd:int"/>
    <part name="faultInt3" type="xsd:int"/>
  </message>

  <message name="IndicPropFault">
    <part name="faultIndic" type="xsd:byte"/>
    <part name="faultProp" type="xsd:string"/>
    <part name="faultText" type="xsd:string"/>
  </message>
  
  <message name="IndicOnlyFault">
    <part name="faultIndic" type="xsd:byte"/>
  </message>
  
  <message name="PropOnlyFault">
    <part name="faultProp" type="xsd:string"/>
  </message>
  
  <!-- port type declns -->
  <portType name="JmsFault">
    <operation name="throwSimple">
      <input message="tns:SimpleReq"/>
      <output message="tns:SimpleResp"/>
      <fault name="SimpleFault" message="tns:SimpleFault"/>
      <fault name="IntFault" message="tns:IntFault"/>
      <fault name="TwoIntFault" message="tns:IntFault"/>
      <fault name="EmptyJmsFault" message="tns:IntFault"/>
    </operation>
    <operation name="throwIndicInt">
      <input message="tns:SimpleReq"/>
      <output message="tns:SimpleResp"/>
      <fault name="SimpleFault" message="tns:SimpleFault"/>
    </operation>
    <operation name="throwProperties">
      <input message="tns:SimpleReq"/>
      <output message="tns:SimpleResp"/>
      <fault name="IndicPropFault" message="tns:IndicPropFault"/>
      <fault name="JmsPropFault" message="tns:IndicPropFault"/>
      <fault name="IndicOnlyFault" message="tns:IndicOnlyFault"/>
      <fault name="PropOnlyFault" message="tns:PropOnlyFault"/>
      <fault name="NullFault" message="tns:SimpleResp"/>
    </operation>
  </portType>

  <!--
  A todo list of other tests that should be included here ...
  - async and sync
  - <fault with and without name="xxx"
  - <fault with and without message="xxx" (don't really know what that means)
  
  Error cases to test ...
  - <jms:faultIndicator type="trash"
  - when the <jms:faultProperty type does not match the real jms property type
  - no type="xxx" in the jms:faultIndicator is an error
  - no name, type, value in the <jms:faultProperty is an error
  - bad parts="xxx" in the <jms:fault 
  - multiple parts="xxx" in the <jms:fault is an error
  - multiple <jms:fault in the <fault is an error
  - multiple faultProperties have the same value
  
  
  A list of unanswered questions 
  - Should multiple <jms:faultIndicator's in the <fault be and'ed or or'ed (I guess and'ed)
  - What if I mix <jms:faultProperty type's?
  - How do other providers handle fault messages? All providers should look the same.
  - How does this work with stubs? How do parts in the fault message get mapped to 
    output parts on the stub?
  - for other providers, WSIF puts a fault string in the fault message ignoring any
    parts in the definition of the fault message. I guess WSIF should use the fault
    message definition but I can't really see how. Maybe WSIF should force the fault
    message to be a string, but that would fail on existing WSDL.
  -->
  
  <binding name="NativeJmsBinding" type="tns:JmsFault">
    <jms:binding type="ObjectMessage"/>
    <format:typeMapping encoding="Java" style="Java">
       <format:typeMap typeName="xsd:string" formatType="java.lang.String" />
    </format:typeMapping>
    <operation name="throwSimple">
      <input/>
      <output/>
      <fault name="SimpleFault">
        <jms:faultIndicator type="property">
          <jms:faultProperty name="faultIndicator" type="xsd:string" value="simple"/>
        </jms:faultIndicator>
      </fault>
      <fault name="IntFault">
        <jms:faultIndicator type="property">
          <jms:faultProperty name="faultIndicator" type="xsd:string" value="ints"/>
        </jms:faultIndicator>
      </fault>
      <fault name="TwoIntFault">
        <jms:faultIndicator type="property">
          <jms:faultProperty name="faultIndicator" type="xsd:string" value="twoints"/>
        </jms:faultIndicator>
        <jms:fault parts="faultInt1 faultInt2"/>
      </fault>
      <fault name="EmptyJmsFault">
        <jms:faultIndicator type="property">
          <jms:faultProperty name="faultIndicator" type="xsd:string" value="ints"/>
        </jms:faultIndicator>
        <jms:fault/>
      </fault>
    </operation>
    <operation name="throwIndicInt">
      <input/>
      <output/>
      <fault name="SimpleFault">
        <jms:faultIndicator type="property">
          <jms:faultProperty name="faultIndicator" type="xsd:int" value="43"/>
        </jms:faultIndicator>
      </fault>
    </operation>
    <operation name="throwProperties">
      <input/>
      <output/>
      <fault name="IndicPropFault">
        <jms:faultIndicator type="property">
          <jms:faultProperty name="faultIndicator" 
                             type="xsd:byte" 
                             value="-1" 
                             part="faultIndic"/>
        </jms:faultIndicator>
        <jms:fault parts="faultText"/>
      </fault>
      <fault name="JmsPropFault">
        <jms:faultIndicator type="property">
          <jms:faultProperty name="faultIndicator" 
                             type="xsd:byte" 
                             value="-2" 
                             part="faultIndic"/>
        </jms:faultIndicator>
        <jms:property name="anotherProperty" 
                      type="xsd:string" 
                      part="faultProp"/>
        <jms:fault parts="faultText"/>
      </fault>
      <fault name="IndicOnlyFault">
        <jms:faultIndicator type="property">
          <jms:faultProperty name="faultIndicator" 
                             type="xsd:byte" 
                             value="-3" 
                             part="faultIndic"/>
        </jms:faultIndicator>
        <jms:fault parts=""/>
      </fault>
      <fault name="PropOnlyFault">
        <jms:faultIndicator type="property">
          <jms:faultProperty name="faultIndicator" 
                             type="xsd:byte" 
                             value="-4" />
        </jms:faultIndicator>
        <jms:property name="anotherProperty" 
                      type="xsd:string" 
                      part="faultProp"/>
      </fault>
      <fault name="NullFault">
        <jms:faultIndicator type="property">
          <jms:faultProperty name="faultIndicator" 
                             type="xsd:byte" 
                             value="-5" />
        </jms:faultIndicator>
      </fault>
    </operation>
  </binding>

  <!-- service decln -->
  <service name="JmsFaultService">
    <port name="default" binding="tns:NativeJmsBinding">
      <jms:address jndiDestinationName="NativeJmsRequestQueue"
                   destinationStyle="queue"
                   jndiConnectionFactoryName="WSIFSampleQCF"
                   initialContextFactory="com.sun.jndi.fscontext.RefFSContextFactory"
                   jndiProviderURL="file://C:/JNDI-Directory"/>
    </port>
  </service>

</definitions>

